// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadAlocQHKY90WqBYNeck3D89CKNcFuK0',
    appId: '1:45236010395:web:a3c49f6b6ae3aca47d753e',
    messagingSenderId: '45236010395',
    projectId: 'posapp-d29ae',
    authDomain: 'posapp-d29ae.firebaseapp.com',
    storageBucket: 'posapp-d29ae.appspot.com',
    measurementId: 'G-PHTLWTQE5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6JbLYQYUH7pkYrJGPpSSDQDGXLnDA2DU',
    appId: '1:45236010395:android:28d58d80e10d7c457d753e',
    messagingSenderId: '45236010395',
    projectId: 'posapp-d29ae',
    storageBucket: 'posapp-d29ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg-mF0Od1kZ1YE-4ECPaF1IhkFggukXSY',
    appId: '1:45236010395:ios:d648c1004b4b89b87d753e',
    messagingSenderId: '45236010395',
    projectId: 'posapp-d29ae',
    storageBucket: 'posapp-d29ae.appspot.com',
    iosClientId: '45236010395-pptkfp0d97hvgu9g9gr2efca39kgbokj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasirDuaputriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg-mF0Od1kZ1YE-4ECPaF1IhkFggukXSY',
    appId: '1:45236010395:ios:d648c1004b4b89b87d753e',
    messagingSenderId: '45236010395',
    projectId: 'posapp-d29ae',
    storageBucket: 'posapp-d29ae.appspot.com',
    iosClientId: '45236010395-pptkfp0d97hvgu9g9gr2efca39kgbokj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kasirDuaputriApp',
  );
}
